public abstract with sharing class AdjudicationWebServiceUtil {
    public class AdjudicationResponse{
        public string TUCANREL4;
        public decimal totalOtherMonthlyExpensesAmount;
        public boolean politicallyExposedInd;
        public boolean otherBeneficiaryInd;
        public string monthsEmployed;
        public decimal monthlyRentPaymentAmount;
        public string maritalStatusCode;
    }
}